sanat = ["aikaikkuna", "värityskirja", "pöytäliina", "uskonto", "mokkula", "sohvapöytä", "kiinankaali", "jääkaappi", "pakastin", "tiedosto",
"aurinko", "merkurius", "venus", "maapallo", "mars", "jupiter", "saturnus", "uranus", "tietokone", "pyörätuoli", "keinutuoli", "eteinen", "pesukone",
"puhelin", "kuutamo", "tammikuu", "helmikuu", "maaliskuu", "huhtikuu", "toukokuu", "kesäkuu", "heinäkuu", "elokuu", "syyskuu", "lokakuu",
"marraskuu", "joulukuu", "talvi", "tavallinen", "kesä", "kevät", "syksy", "erilainen", "kehys", "taulu", "televisio", "liukumäki", "lokki",
"tikka", "kaktus", "kuusi", "koivu", "työturvallisuus", "kahvinkeitin", "maito", "frisbeegolf", "liesituuletin", "kusipää", "kyöpeli", "saatana", "kukkula",
"varjostin", "pyyhe", "hiekka", "ikkuna", "majoneesi", "vyöttää", "kissa", "isoveli", "isosisko", "pikkuveli", "pikkusisko", "aave", "isäpuoli", "äitipuoli",
"kursori", "tomaatti", "kukkakaali", "itsenäinen", "sukkahousut", "jakoavain", "laatikko", "laskin", "historia", "sukellusvene", "naapuri", "sora", "kirahvi",
"virtahepo", "tupsu", "kikatus", "blondi", "prosentti", "tekonurmi", "hiirimatto", "korvamato", "kiuas", "kaula", "sepelvaltimo", "diabetes", "pekoni", "finni",
"lista", "puu", "joulukuusi", "kukkula", "saareke", "nivel", "alkoholi", "allergia", "pasta", "pizza", "ravintola", "näppäimistö", "kruunu", "mestari", "kuningas",
"kuningatar", "prinsessa", "prinssi", "linko", "suihku", "huoneisto", "rappukäytävä", "emoji", "iterointi", "vadelma", "piirakka", "sähkö", "puru", "hammas", "jatkojohto",
"dollari", "kynttilä", "orvokki", "lautanen", "haarukka", "lusikka", "veitsi", "puukottaa", "öljy", "silitysrauta", "punta", "maanosa", "vuokralainen", "laina", "virsi", "kirkko",
"yliopisto", "potkulauta", "polkupyörä", "akseli", "signaali", "logiikka", "jaarittelu", "ärsyttävä", "monsteri", "muija", "jätkä", "spagetti", "ketsuppi", "talo", "perhe",
"perheyritys", "sähköposti", "julkaisu", "media", "omena", "koivu", "siitepöly", "minecraft", "pyyntö", "juoksumatto", "tyttö", "sininen", "punainen", "ruusu", "ornamentti",
"hulvaton", "rajapinta", "integraali", "derivaatta", "tilasto", "binääri", "bitti", "koodikieli", "käärme", "internet", "rengas", "biljardi", "maila", "maantie", "moottori",
"jännitys", "tasapainoelin", "läppä", "tiskiaine", "kylpyamme", "solisluu", "aivopieru", "värimaailma", "ongelma", "peruna", "lanttu", "lompakko", "muistitikku", "peili", "heijastin",
"liikennevalo", "biologia", "lehmä", "utare", "tyynyliina", "pussilakana", "leuka", "paini", "voimannosto", "tutkinto", "aromi", "yhtye", "rannekello", "kaukosäädin", "postimerkki",
"mökki", "käyttäjä", "heroiini", "järvi", "joki", "valtameri", "suo", "koralli", "kilpikonna", "jääkarhu", "maailmanloppu", "saaste", "hiilidioksidi", "pallo", "teatteri", "influenssa",
"rokote", "riskiryhmä", "turvavyö", "penaali", "kuula", "sähköaita", "konvehti", "yhteenlasku", "toiminto", "mustasukkainen", "onnellinen", "negatiivinen", "palmu", "kädellinen", "seinä", "magneetti",
"stressi", "lokero", "baari", "vessa", "keittiö", "fantasia", "pippuri", "tositapahtuma", "näytönkirkkaus", "riittävä", "neule", "villasukka", "yökylä", "terminaali", "pääsiäinen",
"laskiainen", "juhannus", "jumala", "rannikko", "seteli", "alkuperäisasukas", "sana", "kivääri", "revolveri", "parkkikiekko", "hammasharja", "tennismaila", "uimahalli", "yläosa", "kerrossänky",
"kirjasto", "vihollinen", "ötökkä", "ethernet", "suikale", "munakas", "omeletti", "hauta", "videopeli", "hedelmä", "pensas", "sammal", "patsas", "ilmastonmuutos", "posti", "biojäte",
"metalli", "aallonharja", "aamuihminen", "aamukahvi", "aamulypsy", "aamutakki", "aallonpituus", "aallokko", "aamuyö", "tempaus", "tamponi", "juomakelvoton", "oleellinen", "julkinen",
"anoreksia", "hepatiitti", "hiivatulehdus", "eturauhanen", "syöpä", "jalkasieni", "ihottuma", "heinä", "juures", "tammi", "tehtävä", "satula", "päänahka", "sijoitus", "grilli",
"numero", "automaatti", "tuulilasi", "vanne", "kuutio", "heksadesimaali", "yksikkö", "hehtaari", "kokko", "noita", "tulivuori", "tuhka", "polttopuu", "kirves", "desinfiointiaine",
"maski", "kokonaisuus", "pappi", "mestari", "kahvakuula", "ryppy", "pitsi", "numeerinen", "varovainen", "vaikea", "helma", "asento", "armo", "kasvot", "hyräily", "tippua", "säikähdys",
"joukkue", "pelipaita", "katsomo", "päiväkirja", "terapeutti", "kihomato", "saippua", "höylä", "kondomi", "lyijy", "kulta", "hopea", "hampurilainen", "patonki", "viikonloppu", "tuore",
"bataatti", "jalapeno", "keuhkokuume", "keliakia", "pulla", "sämpylä", "vehnäjauho", "isoäiti", "pupilli", "silmälasit", "piilolinssi", "ramppi", "särkylääke", "pilleri", "karva",
"parsakaali", "papu", "yleismittari", "oskilloskooppi", "johde", "pulkka", "peräkärry", "nivelrikko", "melanooma", "nokkonen", "ripuli", "syylä", "ummetus", "vastalääke", "purema",
"huomenna", "turnaus", "taustakuva", "siniaalto", "kolmioaalto", "miinaharava", "monopoli", "lautapeli", "korttipeli", "shakki", "yrittäjä", "ekspertti", "lasta", "rätti", "salmonella",
"sushi", "osasto", "sovituskoppi", "rasia", "säästötili", "laakso", "housut", "nyrkki", "soutu", "jakso", "lompakko", "galaksi", "kapakka", "tonni", "tonnikala", "festivaali", "raaka",
"digitaalinen", "keskitysleiri", "napsauttaa", "lude", "eroosio", "pelletti", "haju", "gorilla", "sokeri", "hiljaisuus", "herra", "tuomaristo", "piirustus", "hermostunut", "helikopteri", "reuna", "lyhyt",
"kaapeli", "taikuri", "paksu", "johdotus", "pannukakku", "kermavaahto", "keramiikka", "savityö", "kuvataide", "museo", "vanhanaikainen", "pyramidi", "kuukautiset", "raskaustesti",
"vaihtoehtoinen", "piraija", "luottamus", "tarjoilija", "kuntosali", "säkki", "kynnysmatto", "kyynärpää", "käsivarsi", "sääri", "takapuoli", "airot", "musikaali", "sorvi", "perusta",
"kivihiili", "bikinit", "sokea", "veri", "viini", "konjakki", "viski", "jääpala", "kabinetti", "piirtotaulu", "paperi", "soija", "vegaani", "hiilihappo", "kivennäisvesi", "karkki", "makeinen",
"pisama", "sorkka", "kynsi", "sakset", "ruutupaperi", "marginaali", "korkokenkä", "aurinkolasit", "kaakao", "kummitus", "luomiväri", "sipuli", "äiti", "napanuora", "istukka", "kätilö",
"toimisto", "talvikengät", "perinteinen", "kuoma", "punatulkku", "joutsen", "löyly", "kuumemittari", "peruukki", "maali", "pensseli", "ratas", "savupiippu", "joulupukki", "turisti",
"kulmakarva", "tomaattimurska", "mozzarella", "sekoitus", "meikkivoide", "puuteri", "pisara", "kyynel", "ympyrä", "rotta", "valaisin", "kysely", "palaute", "valmentaja", "kokkeli",
"aivovaurio", "maanjäristys", "parisuhde", "anonyymi", "mikroskooppi", "miekka", "korkea", "voiteluaine", "banaani", "bambu", "riisi", "maissi", "tasaluku", "neliö", "kolmiodraama",
"asuntovaunu", "karavaani", "varvas", "ripsiväri", "selkä", "materiaali", "nuudeli", "kastike", "jauheliha", "cardio", "omakotitalo", "kuusiaita", "urheilu", "autotalli", "onki",
"koukku", "varjostin", "ensimmäinen", "tapetti", "imuri", "ruutuaika", "diagrammi", "taulukko", "lahja", "myrsky", "myski", "sumu", "ukkonen", "salama", "tappelu", "katkaisin",
"poski", "korttipakka", "lähikauppa", "passi", "makkara", "lenkki", "juutalainen", "humala", "hammasharja", "presidentti", "härkäpapu", "bulevardi", "tiskiharja", "pesukone", "kömpelö",
"uutiset", "aikataulu", "lukujärjestys", "passiivi", "verbi", "substantiivi", "adjektiivi", "olomuoto", "nestemäinen", "sublimointi", "tunnustaa", "valhe", "velho", "askeleet",
"astiakaappi", "komero", "työterveys", "palkki", "virtuaalitodellisuus", "karvanlähtö", "elämänkoulu", "kookospähkinä", "skumppa", "sivupeili", "sademetsä", "popcorn", "jäätelö",
"polkea", "pituushyppy", "keihäs", "käsiraudat", "vatupassi", "oinas", "härkä", "kaksoset", "rapu", "leijona", "neitsyt", "vaaka", "skorpioni", "jousimies", "kauris", "vesimies",
"kalat", "lohikäärme", "vuohi", "horoskooppi", "tähti", "aurinkokunta", "puhveli", "apina", "kukko", "höyhen", "ilmiselvä", "hehkulamppu", "fossiili", "gerbiili", "hamsteri", "nuotti",
"kapellimestari", "orkesteri", "viulu", "tuuba", "kitara", "onkalo", "kuihtua", "nielurisat", "kuorsaus", "vakuutus", "ruokahävikki", "linkki", "paniikki", "lyhty", "amuletti",
"salkku", "tarjous", "marmeladi", "joulukinkku", "lahjapaperi", "ilmastointi", "niitti", "poro", "luonnollinen", "pystysuora", "huuhdella", "trampoliini", "sketsi", "viisumi",
"keinohedelmöitys", "sateenkaari", "avocado", "curry", "poncho", "piknik", "galvanoida", "sarjakuva", "generaattori", "pääkallo", "luuranko", "alkuluku", "kettu", "katketa", "roikkua",
"viekas", "tasajakauma", "pikajuna", "pendolino", "lentolippu", "ulkomaa", "matkamuisto", "modeemi", "moduuli", "iltapäivä", "välipala", "jooga", "vasemmisto", "geokätkö",
"vitamiini", "mineraali", "katkoviiva", "trukki", "tsunami", "lumivyöry", "mörkö", "kierroslukumittari", "hunaja", "tulevaisuus", "mehiläinen", "viidakko", "liaani", "violetti",
"purppura", "antibiootti", "meloni", "muskotti", "tulitikku", "halkeama", "liikkumaton", "naarmu", "kolari", "pilleri", "kansio", "ambulanssi", "ensiapu", "lauhkea", "tundra",
"kasvillisuusvyöhyke", "karate", "savanni", "hormoni", "postikortti", "vasen", "persilja", "horisontti", "liha", "lonkka", "viisaudenhammas", "mobiili", "hanuri", "iilimato",
"faksi", "käsinukke", "lapsellinen", "pirtti", "huussi", "vasara", "reititin", "pultti", "riippumatto", "ilotulitus", "pääsykoe", "kobra", "akvaario", "ultraviolettisäteily",
"asiakaspalvelu", "insinööri", "virpoa", "maastokuvio", "läpinäkyvä", "visuaalinen", "auditiivinen", "sanko", "ämpäri", "vedenkestävä", "suurennuslasi", "muurahainen", "neulanen",
"viileä", "kangas", "kenguru", "testamentti", "maistraatti", "vauva", "sikiö", "kasvukipu", "päähenkilö", "sivuhenkilö", "kertoja", "siili", "purukumi", "ksylitoli",
"kosketusnäyttö", "aurinkopaneeli", "itserusketus", "tahmainen", "selkäranka", "skolioosi", "puolueellinen", "keskittyä", "luento", "sandaali", "sardiini", "oisteri",
"simpukka", "vartalo", "ruukkukasvi", "röyhkeä", "tikapuut", "nuohooja", "kyseenalainen", "viikset", "pedofiili", "kysymys", "tuomio", "valvontakamera", "järjestelmänvalvoja",
"tietoliikenne", "salasana", "salmiakki", "torni", "sohvapöytä", "astronautti", "johdonmukainen", "kaulakoru", "sormus", "tuuma", "napapaita", "servetti", "kattaus",
"tuoppi", "tiskijukka", "shotti", "kotiavain" "pyörävarasto", "kirpputori", "tilinumero", "allekirjoitus", "pankkikortti", "kattila", "soppa", "mansikka", "smokki", "pimeähkö",
"joutava", "lihaskunto", "pesäpallo", "isänmaa", "laituri", "auringonlasku", "mitali", "sekunti", "tusina", "plasma", "silikoni", "kondensaattori", "muuntaja", "puolikuu",
"seitsenkulmio", "soikea", "vinoneliö", "leikepöytä", "tutti", "krokotiili", "akne", "delfiini", "miekkavalas", "aprikoosi", "lypsää", "neljäsosa", "komplikaatio", "symmetria",
"ristikko", "sijainti", "säde", "bingo", "dinosaurus", "karamelli", "kokonainen", "avojaloin", "laboatorio", "palmikko", "sisusta", "kaava", "hypnotisoida",
"ksylofoni", "itämainen", "saippua", "heimo", "olut", "leppäkerttu", "juustohöylä", "tuutti", "maantiede", "kondiittori", "lääkäri", "tohtori", "aasi", "kovera", "asteikko",
"oliivi", "coctail", "astiasto", "selain", "kirjahylly", "huuhteluaine", "taivas", "pilvi", "pouta", "yksimielinen", "diktaattori", "raide", "kampaaja", "nuoli", "kieli",
"lävistys", "tatuointi", "munkki", "herkullinen", "perunalastu", "fenkoli", "lisäaine", "maissitärkkelys", "etikka", "yhteiskunta", "kellonaika", "varsi", "äänensävy",
"turbiini", "kivikausi", "kalevala", "kansallislaulu", "kurpitsa", "munakoiso", "lainausmerkki", "kahvitauko", "siivouspäivä", "hakemisto", "irtaimisto", "vasikka", "lempeä",
"lemmikki", "kuntopyörä", "vandalismi", "konkurssi", "testiryhmä", "kohouma", "paloauto", "purjehtia", "nakki", "kolibri", "siemen", "tyytyväinen", "erikseen", "aterimet",
"steriili", "steroidi", "ympärysmitta", "uhanalainen", "kirjava", "naaras", "huulet", "huulipuna", "tilli", "puuro", "sytkä", "tupakka", "raketti", "ampumahiihto", "suunnistus",
"kompassi", "hiilijalanjälki", "viinirypäle", "laventeli", "vanilja", "itserakas", "romanssi", "kulmikas", "trooppinen", "palatsi", "teelusikka", "viimeinen"]
